#!/bin/sh
 
PROJECT=$(php -r "echo dirname(dirname(dirname(realpath('$0'))));")
 
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi
 
STAGED_FILES_CMD=$(git diff --cached --name-only --diff-filter=ACMR $against| grep .php)
 
# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}
 
echo "Checking PHP Lint..."
for FILE in $SFILES ; do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done
 
if [ "$SFILES" != "" ]
then
    echo "Running Code Sniffer."
    phpcs --standard=./dev-tools/php-codesniffer-rules/FDStandard/ruleset.xml $FILES
fi
 
exit $?
